### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by Senjuti** [doefler/Instagram-growth#2]
I tried running your script on the browser and the command line.
When opened in the browser (http://localhost/instagram-growth.php) I see the following output:
Array
(
    [0] => 
    [1] => 
    [2] => 
)

When run on the command line with the following command:
php instagram-growth.php 

I see this output:
 Invalid argument supplied for foreach() in /var/www/html/instagram-growth.php on line 12
PHP Notice:  Undefined variable: data in /var/www/html/instagram-growth.php on line 55
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/instagram-growth.php on line 12
PHP Notice:  Undefined variable: data in /var/www/html/instagram-growth.php on line 55
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/instagram-growth.php on line 12
PHP Notice:  Undefined variable: data in /var/www/html/instagram-growth.php on line 55
<pre>Array
(
    [0] => 
    [1] => 
    [2] => 
)

**Comment by doefler** [comment]
Hey @Senjuti I am sorry for the error.
I think it is due to updates of the Instagram API.
See #1 for a solution.

Have a nice day :smile:
