### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rx2s1987** [doefler/Instagram-growth#4]
If i want to start the script a second time i get this error.

php insta.php
PHP Notice:  Undefined index: data in /tmp/test/secure/insta.php on line 12
PHP Warning:  Invalid argument supplied for foreach() in /tmp/test/secure/insta.php on line 12
PHP Notice:  Undefined variable: data in /tmp/test/secure/insta.php on line 55
<pre>Array
(
    [0] =>
)

**Comment by doefler** [comment]
Hi @Rx2s1987 please see #1
